## Modules

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

## Load data

In [2]:
data = pd.read_csv("AnunciosRedesSociales.csv")

In [3]:
X= data.iloc[:,[2,3]].values
y= data.iloc[:,4].values

### Split and scaler data

In [4]:
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=.25, random_state=0)

In [5]:
sx= StandardScaler()
x_train = sx.fit_transform(x_train)
x_test= sx.fit_transform(x_test)

## Modeling

### Suport Vector Machine

In [6]:
classificador= SVC(kernel="poly",degree=5,random_state=0)
classificador.fit(x_train, y_train)

SVC(degree=5, kernel='poly', random_state=0)

In [7]:
y_predice= classificador.predict(x_test)

In [10]:
confusion_matrix(y_test,y_predice)

array([[65,  3],
       [13, 19]], dtype=int64)

In [12]:
precisionSVC= cross_val_score(estimator=classificador, X=x_train, y= y_train, cv=10)

### Logistica

In [11]:
regLog= LogisticRegression()
regLog.fit(x_train,y_train)

LogisticRegression()

In [12]:
y_log= regLog.predict(x_test)

In [13]:
confusion_matrix(y_test,y_log)

array([[63,  5],
       [ 8, 24]], dtype=int64)

In [14]:
precisionLog= cross_val_score(estimator=regLog, X=x_train, y= y_train, cv=10)

## Arboles

In [15]:
tree= DecisionTreeClassifier()
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
y_tree= tree.predict(x_test)

In [17]:
confusion_matrix(y_test,y_tree)

array([[61,  7],
       [ 5, 27]], dtype=int64)

In [18]:
precisionTree= cross_val_score(estimator=tree, X=x_train, y= y_train, cv=10)

## Results

In [29]:
print(f"SVC mean: {precisionSVC.mean()}, SVC std: {precisionSVC.std()}\nLogistic regression mean: {precisionLog.mean()}, Logistic regression std: {precisionLog.std()}\nTree mean: {precisionTree.mean()}, Tree std: {precisionTree.std()}  ")

SVC mean: 0.8033333333333333, SVC std: 0.06574360974438676
Logistic regression mean: 0.8233333333333335, Logistic regression std: 0.09666666666666669
Tree mean: 0.8566666666666667, Tree std: 0.051747248987533426  
