In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("AnunciosRedesSociales.csv")

In [4]:
X= data.iloc[:,[2,3]].values
y= data.iloc[:,4].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=.25, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sx= StandardScaler()
x_train = sx.fit_transform(x_train)
x_test= sx.fit_transform(x_test)

In [10]:
from sklearn.svm import SVC

In [11]:
classificador= SVC(kernel="poly",degree=5,random_state=0)
classificador.fit(x_train, y_train)

SVC(degree=5, kernel='poly', random_state=0)

In [12]:
y_predice= classificador.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix

In [15]:
cm=confusion_matrix(y_test,y_predice)

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
precision= cross_val_score(estimator=classificador, X=x_train, y= y_train, cv=10)

In [20]:
precision.mean()

0.8033333333333333

In [21]:
precision.std()

0.06574360974438676

In [35]:
precision

array([0.83333333, 0.83333333, 0.7       , 0.83333333, 0.8       ,
       0.7       , 0.8       , 0.93333333, 0.83333333, 0.76666667])

## logistica

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
regLog= LogisticRegression()
regLog.fit(x_train,y_train)

LogisticRegression()

In [25]:
y_log= regLog.predict(x_test)

In [26]:
cm=confusion_matrix(y_test,y_log)

In [27]:
precisionLog= cross_val_score(estimator=regLog, X=x_train, y= y_train, cv=10)

In [28]:
(precisionLog.mean(), precisionLog.std())

(0.8233333333333335, 0.09666666666666669)

## Arboles

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [30]:
tree= DecisionTreeClassifier()
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [31]:
y_tree= tree.predict(x_test)

In [32]:
cm=confusion_matrix(y_test,y_tree)

In [33]:
precisionTree= cross_val_score(estimator=tree, X=x_train, y= y_train, cv=10)

In [34]:
(precisionTree.mean(), precisionTree.std())

(0.86, 0.05333333333333336)

In [36]:
precisionTree

array([0.83333333, 0.83333333, 0.73333333, 0.9       , 0.86666667,
       0.83333333, 0.9       , 0.86666667, 0.9       , 0.93333333])

In [37]:
precisionLog

array([0.76666667, 0.86666667, 0.73333333, 0.86666667, 0.7       ,
       0.66666667, 0.83333333, 0.93333333, 0.96666667, 0.9       ])