# Pytorch

## Modules

In [1]:
import torch
import numpy as np

## Create a tensor

In [4]:
torch_array = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print("Tensor array: \n\n",torch_array)

Tensor array: 

 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Created functions

### Rand

In [5]:
torch_rand = torch.rand(3,3)
print("\n Random matrix with Pytorch: \n")
print(torch_rand,"\n")
print(torch_rand.shape)


 Random matrix with Pytorch: 

tensor([[0.4320, 0.2587, 0.3956],
        [0.8536, 0.0114, 0.8287],
        [0.4775, 0.3455, 0.8993]]) 

torch.Size([3, 3])


### Identity

In [6]:
torch_id = torch.eye(3)
print(torch_id)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Multiplication

In [7]:
torch_a1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch_a2 = torch.tensor([[2,3],[2,3],[2,3]])
print(torch.mm(torch_a1,torch_a2))

tensor([[12, 18],
        [30, 45],
        [48, 72]])


In [8]:
print(torch_a1 * 2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])


## Derivate

In [9]:
x1 = torch.tensor([2.0], requires_grad=True).float()
z1 = x1
x2 = torch.tensor([2.0], requires_grad=True).float()
z2 = x2**2
x3 = torch.tensor([2.0], requires_grad=True).float()
z3 = x3**3

In [11]:
z1.backward()
z2.backward()
z3.backward()

In [17]:
print('dz1/dx1 evaluated in %f: %f' % (x1, x1.grad)) # dz1/dx = 1
print('dz2/dx2 evaluated in %f: %f' % (x2, x2.grad)) # dz2/dx = 2 * 2
print('dz3/dx3 evaluated in %f: %f' % (x3, x3.grad)) # dz3/dx = 3 * 4

dz1/dx1 evaluated in 2.000000: 1.000000
dz2/dx2 evaluated in 2.000000: 4.000000
dz3/dx3 evaluated in 2.000000: 12.000000


## Sinlgle layer

In [25]:
def sigm(x):
    return 1/(1+torch.exp(-x))
    
torch.manual_seed(7)

inputs = torch.randn((1,10))
w1 = torch.randn_like(inputs) ## Tensor de la misma dimension pero random
b1 = torch.randn((1,1))

### Ways to reshape tensor 

Retornar un tensor con la dimensiones especificadas

In [31]:
w1.reshape(10,1)
w1.view(10,1)   

tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])

Cambia las dimensiones del tensor y las guarda en el mismo

In [32]:
w1.resize_(10,1)

tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])

In [34]:
output = sigm(torch.matmul(inputs,w1)+b1)
print(output)

tensor([[0.3030]])


## NN 2 hiden layers

In [ ]:
input_layer = torch.rand(10)
print(input_layer.shape)

#h1 contains 20 units
w1 = torch.rand(10,20)
b1 = torch.randn(20)
#h2 contains 20 units
w2 = torch.rand(20,20)
b2 = torch.randn(20)
#the output layer has 10 units
w3 = torch.rand(20,10)
b3 = torch.randn(10)

h1 = torch.matmul(w1.T,input_layer)+b1
print("First hidden layer:")
print(h1,"\n")
h2 = torch.matmul(w2.T,h1)+b2
print("Second hidden layer:")
print(h2,"\n") 
output_layer = torch.matmul(w3.T,h2)+b3
print("Output layer:")
print(output_layer)

## NN from nn.MOdule

In [35]:
import torch.nn as nn

#class Net inherits from nn.Module
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # nn.Linear(i,o) where i=# units in the current layer, o = # units in the next layer
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,20)
        self.out = nn.Linear(20,10)
        
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        return x
      
input_layer = torch.rand(10)
#instantiate model
net = Net()
result = net(input_layer)
print(result)      

tensor([ 0.1782, -0.0429, -0.2798,  0.0744, -0.0785, -0.1032,  0.6252,  0.0890,
         0.1006,  0.0191], grad_fn=<AddBackward0>)
