# Pytorch

## Modules

In [1]:
import torch
import numpy as np

## Create a tensor

In [2]:
torch_array = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print("Tensor array: \n\n",torch_array)

Tensor array: 

 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Created functions

### Rand

In [3]:
torch_rand = torch.rand(3,3)
print("\n Random matrix with Pytorch: \n")
print(torch_rand,"\n")
print(torch_rand.shape)


 Random matrix with Pytorch: 

tensor([[0.9086, 0.5186, 0.4023],
        [0.5587, 0.3852, 0.4310],
        [0.4627, 0.2453, 0.8882]]) 

torch.Size([3, 3])


### Identity

In [4]:
torch_id = torch.eye(3)
print(torch_id)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Multiplication

In [5]:
torch_a1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch_a2 = torch.tensor([[2,3],[2,3],[2,3]])
print(torch.mm(torch_a1,torch_a2))

tensor([[12, 18],
        [30, 45],
        [48, 72]])


In [6]:
print(torch_a1 * 2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])


## Derivate

In [7]:
x1 = torch.tensor([2.0], requires_grad=True).float()
z1 = x1
x2 = torch.tensor([2.0], requires_grad=True).float()
z2 = x2**2
x3 = torch.tensor([2.0], requires_grad=True).float()
z3 = x3**3

In [8]:
z1.backward()
z2.backward()
z3.backward()

In [9]:
print('dz1/dx1 evaluated in %f: %f' % (x1, x1.grad)) # dz1/dx = 1
print('dz2/dx2 evaluated in %f: %f' % (x2, x2.grad)) # dz2/dx = 2 * 2
print('dz3/dx3 evaluated in %f: %f' % (x3, x3.grad)) # dz3/dx = 3 * 4

dz1/dx1 evaluated in 2.000000: 1.000000
dz2/dx2 evaluated in 2.000000: 4.000000
dz3/dx3 evaluated in 2.000000: 12.000000


## Neural Networks

### Sinlgle layer

In [10]:
def sigm(x):
    return 1/(1+torch.exp(-x))
    
torch.manual_seed(7)

inputs = torch.randn((1,10))
w1 = torch.randn_like(inputs) ## Tensor de la misma dimension pero random
b1 = torch.randn((1,1))

#### Ways to reshape tensor 

Retornar un tensor con la dimensiones especificadas

In [11]:
w1.reshape(10,1)
w1.view(10,1)   

tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])

Cambia las dimensiones del tensor y las guarda en el mismo

In [12]:
w1.resize_(10,1)

tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])

In [13]:
output = sigm(torch.matmul(inputs,w1)+b1)
print(output)

tensor([[0.3030]])


## NN 2 hiden layers

In [14]:
input_layer = torch.rand(10)
print(input_layer.shape)

#h1 contains 20 units
w1 = torch.rand(10,20)
b1 = torch.randn(20)
#h2 contains 20 units
w2 = torch.rand(20,20)
b2 = torch.randn(20)
#the output layer has 10 units
w3 = torch.rand(20,10)
b3 = torch.randn(10)

h1 = torch.matmul(w1.T,input_layer)+b1
print("First hidden layer:")
print(h1,"\n")
h2 = torch.matmul(w2.T,h1)+b2
print("Second hidden layer:")
print(h2,"\n") 
output_layer = torch.matmul(w3.T,h2)+b3
print("Output layer:")
print(output_layer)

torch.Size([10])
First hidden layer:
tensor([2.8571, 4.5964, 2.7061, 1.6105, 4.0433, 1.6860, 3.6443, 2.1050, 3.9807,
        3.4162, 2.5031, 1.6862, 2.9572, 2.2082, 3.2833, 3.7847, 2.7327, 2.6177,
        1.2653, 5.9995]) 

Second hidden layer:
tensor([32.2993, 23.9020, 20.6125, 30.9846, 30.5237, 41.0882, 27.3729, 29.6121,
        28.8898, 33.0395, 31.6494, 33.4028, 31.4145, 28.3931, 29.2206, 26.7620,
        29.9971, 33.3539, 24.0110, 28.0911]) 

Output layer:
tensor([267.5026, 292.9840, 243.6890, 277.8268, 314.4776, 387.0657, 258.0089,
        334.9822, 283.3747, 273.0109])


## NN as a class

In [35]:
import torch.nn as nn

#class Net inherits from nn.Module
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # nn.Linear(i,o) where i=# units in the current layer, o = # units in the next layer
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,20)
        self.out = nn.Linear(20,10)
        
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        return x
      
input_layer = torch.rand(10)
#instantiate model
net = Net()
result = net(input_layer)
print(result)      

tensor([ 0.1782, -0.0429, -0.2798,  0.0744, -0.0785, -0.1032,  0.6252,  0.0890,
         0.1006,  0.0191], grad_fn=<AddBackward0>)
